[package]
name = "rbfc"
version = "0.1.0"
authors = ["Thomas Saint-GÃ©rand <devspaceship@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
